# Start the gpg-agent as a daemon; that is, detach it from the console and run it in the background.
#   As an alternative you may create a new process as a child of gpg-agent: gpg-agent --daemon /bin/sh.
#   This way you get a new shell with the environment setup properly; after you exit from this shell,
#   gpg-agent terminates within a few seconds.
daemon

# This option allows the use of gpg-preset-passphrase to seed the internal cache
# of gpg-agent with passphrases.
allow-preset-passphrase
allow-loopback-pinentry

# This option is only useful for debugging and the behavior may change at any time without notice.
# FLAGS are bit encoded and may be given in usual C-Syntax.
debug-all
extra-socket /etc/gnupg/S.local-agent
extra-socket /etc/gnupg/S.local-agent.extra
browser-socket /etc/gnupg/S.local-agent.browser

