---
- name: Check if GPG private key exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}/private/repo_signing_private.key"
  register: packtly_secrets_gpg_key_stat

- name: Check if SSH key exists
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}/ssh/id_ed25519"
  register: packtly_secrets_ssh_key_stat

- name: Check if API credentials exist
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}/public/.htpasswd"
  register: packtly_secrets_api_credentials_stat

- name: Determine if secret generation is required
  ansible.builtin.set_fact:
    packtly_secrets_packtly_secrets_secrets_missing: >
      {{ not packtly_secrets_gpg_key_stat.stat.exists
         or not packtly_secrets_ssh_key_stat.stat.exists
         or not packtly_secrets_api_credentials_stat.stat.exists }}

- name: Ensure secret directory exists
  ansible.builtin.file:
    path: "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}"
    state: directory
    mode: "0700"

- name: Ensure secret subdirectories exist
  ansible.builtin.file:
    path: "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}/{{ item }}"
    state: directory
    mode: "0700"
  loop:
    - private
    - public
    - ssh

- name: Start setup container
  containers.podman.podman_container:
    name: "{{ packtly_secrets_setup_container }}"
    image: "{{ container_registry if container_method == 'pull' else container_image_local }}"
    state: started
    hostname: "{{ app_name }}"
    recreate: true
    detach: true
    volume:
      - "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}:/opt/packtly"
      - "{{ playbook_dir }}/generated-secrets/{{ inventory_hostname }}/private:/run/secrets"
    command: sleep infinity
  when: packtly_secrets_packtly_secrets_secrets_missing

- name: Ensure SSH keys exist inside container
  containers.podman.podman_container_exec:
    name: "{{ packtly_secrets_setup_container }}"
    command: >-
      bash -euo pipefail -c '
      mkdir -p /opt/packtly/ssh

      test -f /opt/packtly/ssh/id_ed25519 ||
      dropbearkey
      -C "noname"
      -q
      -t ed25519
      -N ""
      -f /opt/packtly/ssh/id_ed25519

      test -f /opt/packtly/ssh/id_ed25519.openssh ||
      dropbearconvert
      dropbear
      openssh
      /opt/packtly/ssh/id_ed25519
      /opt/packtly/ssh/id_ed25519.openssh
      '
  when:
    - packtly_secrets_packtly_secrets_secrets_missing
    - not packtly_secrets_ssh_key_stat.stat.exists

- name: Generate GPG key
  containers.podman.podman_container_exec:
    name: "{{ packtly_secrets_setup_container }}"
    command: >
      gen_gpg --name "{{ gpg_user }}" --email "{{ gpg_email }}" --pass "{{ gpg_pass }}"
  when:
    - packtly_secrets_packtly_secrets_secrets_missing
    - not packtly_secrets_gpg_key_stat.stat.exists

- name: Generate API credentials
  containers.podman.podman_container_exec:
    name: "{{ packtly_secrets_setup_container }}"
    command: >
      gen_htpasswd "{{ api_user }}" "{{ api_pass }}"
  when:
    - packtly_secrets_packtly_secrets_secrets_missing
    - not packtly_secrets_api_credentials_stat.stat.exists

- name: Remove setup container
  containers.podman.podman_container:
    name: "{{ packtly_secrets_setup_container }}"
    state: absent
  when: packtly_secrets_packtly_secrets_secrets_missing
