---
- name: Print container method
  ansible.builtin.debug:
    msg: "Container method is set to '{{ container_method }}'"

- name: Podman login (rootless)
  containers.podman.podman_login:
    registry: "{{ container_registry_url }}"
    username: "{{ container_registry_username }}"
    password: "{{ container_registry_password }}"
  when: container_registry_auth | default(false)

- name: Pull image from registry
  containers.podman.podman_image:
    name: "{{ container_registry }}"
    pull: true
    state: present

