# /etc/nginx/nginx.conf

events {}

http {
    # Set server names hash bucket size for efficient name resolution
    server_names_hash_bucket_size 64;

    # Disable NGINX server tokens to hide version information
    server_tokens off;

    include /etc/nginx/conf.d/*.conf;
}
