---
- name: Create a temporary directory
  ansible.builtin.tempfile:
    state: directory
    suffix: pip_config
  register: container_runtime_temp_dir

- name: Copy pip.conf template to temp directory
  ansible.builtin.template:
    src: pip.conf.j2
    dest: "{{ container_runtime_temp_dir.path }}/pip.conf"
    mode: "0600"

- name: Display the temporary path
  ansible.builtin.debug:
    msg: "pip.conf deployed to {{ container_runtime_temp_dir.path }}/pip.conf"
