---
- name: Stop and remove container service
  ansible.builtin.include_tasks: teardown.yml
- name: Pull container image if selected
  ansible.builtin.include_tasks: image_pull.yml
  when: container_method == 'pull'

- name: Build container image if selected
  ansible.builtin.include_tasks: image_build.yml
  when: container_method == 'build'

- name: Create packtly volume
  ansible.builtin.include_tasks: volume.yml
- name: Provision of the packtly volume
  ansible.builtin.include_tasks: provision.yml
- name: Start container service
  ansible.builtin.include_tasks: service.yml
