---
- name: Print container method
  ansible.builtin.debug:
    msg: "Container method is set to '{{ container_method }}'"
  delegate_to: localhost
  become: false

- name: Get Git top-level directory
  ansible.builtin.command: git rev-parse --show-toplevel
  register: git_topdir
  changed_when: false
  delegate_to: localhost
  become: false

- name: Debug Git top-level directory
  ansible.builtin.debug:
    msg: "Git top directory is {{ git_topdir.stdout }}"
  delegate_to: localhost
  become: false

- name: Remove existing local image
  containers.podman.podman_image:
    name: "{{ container_image_local }}"
    state: absent
    force: true
  when: container_force_rebuild
  delegate_to: localhost
  become: false

- name: Build the container locally
  containers.podman.podman_image:
    name: "{{ container_image_local }}"
    tag: latest
    path: "{{ git_topdir.stdout | trim }}/packtly-infra"  # Build context matches Containerfile location
    state: present
    build:
      file: "Containerfile"  # Relative to `path`
      extra_args: "{{ '--secret=id=pip.conf,src=' + (temp_dir | default({})).get('path', '') + '/pip.conf' if (temp_dir | default({})).get('path') else '' }}"
  delegate_to: localhost
  become: false

- name: Define image archive path
  ansible.builtin.set_fact:
    image_archive: "/tmp/{{ container_image_local | replace(':', '_') }}.tar"

- name: Export locally built image
  containers.podman.podman_save:
    image: "{{ container_image_local }}"
    dest: "{{ image_archive }}"
  delegate_to: localhost
  become: false

- name: Copy image archive to remote host
  ansible.builtin.copy:
    src: "{{ image_archive }}"
    dest: "{{ image_archive }}"
    mode: "0644"

- name: Load image from tar archive
  containers.podman.podman_load:
    input: "{{ image_archive }}"

- name: Remove remote image archive
  ansible.builtin.file:
    path: "{{ image_archive }}"
    state: absent
  become: false

- name: Remove local image archive
  ansible.builtin.file:
    path: "{{ image_archive }}"
    state: absent
  delegate_to: localhost
  become: false

- name: Cleanup local temp dir
  ansible.builtin.file:
    path: "{{ temp_dir.path }}"
    state: absent
  when: temp_dir is defined and temp_dir.path is defined
  delegate_to: localhost
  become: false
