---
- name: Start the Podman container
  containers.podman.podman_container:
    name: "{{ packtly_service_setup_container }}"
    image: "{{ container_registry if container_method == 'pull' else container_image_local }}"
    state: started
    hostname: "{{ app_name }}"
    recreate: true
    detach: true
    volume:
      - "packtly_data:/opt/packtly"
    secrets:
      - packtly_gpg_private_key
      - packtly_gpg_passphrase
    command: sleep infinity

- name: Import GPG key
  containers.podman.podman_container_exec:
    name: "{{ packtly_service_setup_container }}"
    command: >
      /usr/local/bin/entrypoint_gpg

- name: Create repos
  containers.podman.podman_container_exec:
    name: "{{ packtly_service_setup_container }}"
    command: "{{ item }}"
  loop:
    - create_repo -d trixie-apollo -c main -m "Embtom trixie" -n trixie-apollo-main
    - create_repo -d trixie-apollo -c contrib -m "Embtom trixie" -n trixie-apollo-contrib
    - publish_repo -r trixie-apollo-main,trixie-apollo-contrib

- name: Remove the Podman container after finish
  containers.podman.podman_container:
    name: "{{ packtly_service_setup_container }}"
    state: absent
