name: ci-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-24.04
    permissions: 
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare build environment
        uses: ./.github/actions/setup-podman

      - name: Get release version
        id: context
        uses: ./.github/actions/get-version

      - name: Version
        run: echo "Release version is ${{ steps.context.outputs.release_version }}"

      - name: Build image
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ github.repository }}
          tags: latest
          containerfiles: packtly-infra/Containerfile
          context: packtly-infra
          build-args: VERSION=${{ steps.context.outputs.release_version }}
          oci: true

      - name: Log in to ghcr.io
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build.outputs.image }}
          tags: latest
          registry: ghcr.io
