LogLevel INFO
AllowUsers root
PubkeyAuthentication yes
PasswordAuthentication no
PermitRootLogin yes
PermitEmptyPasswords no
Protocol 2
# AllowTcpForwarding yes
# AllowTcpForwarding yes
# GatewayPorts yes
# TCPKeepAlive yes

